# Generated by Django 4.0.4 on 2022-06-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_annotation_tool', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='id',
        ),
        migrations.AlterField(
            model_name='feed',
            name='title',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
