# Generated by Django 4.0.4 on 2022-06-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_annotation_tool', '0002_remove_feed_id_alter_feed_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedArticle',
            fields=[
                ('title', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('comment', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Feed',
        ),
    ]
