# Generated by Django 4.0.4 on 2022-06-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_annotation_tool', '0004_feedarticle_bookmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedarticle',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
