# Generated by Django 4.0.4 on 2022-06-08 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss_annotation_tool', '0005_alter_feedarticle_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedarticle',
            old_name='comment',
            new_name='comments',
        ),
    ]
